# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import meter_pb2 as meter__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in meter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MeterReadingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IssueMeterReading = channel.unary_stream(
                '/MeterReading/IssueMeterReading',
                request_serializer=meter__pb2.MeterReadingRequest.SerializeToString,
                response_deserializer=meter__pb2.MeterReadingReply.FromString,
                _registered_method=True)


class MeterReadingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IssueMeterReading(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeterReadingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IssueMeterReading': grpc.unary_stream_rpc_method_handler(
                    servicer.IssueMeterReading,
                    request_deserializer=meter__pb2.MeterReadingRequest.FromString,
                    response_serializer=meter__pb2.MeterReadingReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MeterReading', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MeterReading', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MeterReading(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IssueMeterReading(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/MeterReading/IssueMeterReading',
            meter__pb2.MeterReadingRequest.SerializeToString,
            meter__pb2.MeterReadingReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
